<?php

return [
    'enum_paths' => [
        base_path('app/Enums'),
    ],
    'output_path' => resource_path('js/enums'),
    'format' => 'js',
    'banner' => '// AUTO-GENERATED FILE. Do not edit this file. (use command: `php artisan atlas:export-enums`)',
];
